// !!!!!! DO NOT EDIT THIS FILE INSIDE A CHILD NOAK-TEMPLATE !!!!!!!
// https://chakra-ui.com/docs/theming/customize-theme

import { extendTheme } from '@chakra-ui/react';
import { defaultTheme } from './default.lock';
import { customTheme } from './custom';

export const overrideTheme = { ...defaultTheme, ...customTheme };

const theme = extendTheme(overrideTheme);

export default theme;
