// !!!!!! DO NOT EDIT THIS FILE INSIDE A CHILD NOAK-TEMPLATE !!!!!!!
import NextExperimental from './experimental';
import NextHeaders from './headers';
import NextRedirects from './redirects';
import NextRewrites from './rewrites';
import NextImageDomains from './images';
import NextCompiler from './compiler';

const DefaultNextConf = {
  // https://nextjs.org/docs/api-reference/next.config.js/react-strict-mode
  reactStrictMode: true,

  // https://nextjs.org/docs/upgrading#swc-replacing-babel
  swcMinify: true,

  // unstable features
  experimental: NextExperimental,

  compiler: NextCompiler,

  // https://nextjs.org/docs/api-reference/next.config.js/headers
  async headers() {
    return [
      {
        source: '/(.*)',
        headers: NextHeaders,
      },
    ];
  },

  // https://nextjs.org/docs/api-reference/next.config.js/redirects
  async redirects() {
    return NextRedirects;
  },

  // https://nextjs.org/docs/api-reference/next.config.js/rewrites
  async rewrites() {
    return NextRewrites;
  },

  // https://nextjs.org/docs/basic-features/image-optimization#domains
  images: {
    domains: NextImageDomains,
  },
};

export default DefaultNextConf;
